# Generated by Django 3.2.22 on 2023-11-12 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subscribe_newsletter',
            field=models.BooleanField(default=False),
        ),
    ]
