# Generated by Django 3.2.22 on 2023-12-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='category',
        ),
        migrations.AddField(
            model_name='contactus',
            name='wedding',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
