# Generated by Django 3.2.22 on 2023-10-27 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20231026_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sizeable',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
