# Generated by Django 3.2.22 on 2023-11-10 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_sizeable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='engrave_cost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='engrave_style',
        ),
        migrations.RemoveField(
            model_name='product',
            name='engrave_text',
        ),
        migrations.AddField(
            model_name='product',
            name='engrave',
            field=models.BooleanField(default=False),
        ),
    ]
